# Generated by Django 4.1 on 2022-09-08 23:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('text', models.TextField(max_length=2000)),
                ('edit_count', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='travel_app/images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
                ('edit_count', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='travel_app/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('edit_count', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='travel_app/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('summary', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=1000)),
                ('image', models.ImageField(default='travel_app/images/default.jpg', upload_to='travel_app/images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_app.category')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
