# Generated by Django 4.1 on 2022-09-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='/media/travel_app/images/', upload_to='travel_app/images/'),
        ),
    ]
